### ISSUE TITLE
Revise servant-0.14.1 to allow base-4.12 (ghc 8.6)

### ISSUE THREAD

**Issue by DanBurton** [haskell-servant/servant#1049]
I was able to get the `servant-0.14.1` tarball to build with `base-4.12.0.0` by changing only the constraints on `base`. My steps to reproduce (passing tests):

```bash
stack unpack servant-0.14.1 && cd servant-0.14.1
edit servant.cabal # relax constraints on base
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: nightly-2018-10-10
extra-deps:
- http-media-0.7.1.3@sha256:7dbecedbc049ac8863f8cd18755eba5fdf4a165d324195ae918b97e8b8f17198

```

See also: https://github.com/haskell-servant/servant/pull/1045
