### ISSUE TITLE
Need a way to return 201 Created as the result of a PUT

### ISSUE THREAD

**Issue by Porges** [haskell-servant/servant#189]
Per [RFC7321](https://tools.ietf.org/html/rfc7231#section-4.3.4):

> If the target resource does not have a current representation and the
   PUT successfully creates one, then the origin server MUST inform the
   user agent by sending a 201 (Created) response.  If the target
   resource does have a current representation and that representation
   is successfully modified in accordance with the state of the enclosed
   representation, then the origin server MUST send either a 200 (OK) or
   a 204 (No Content) response to indicate successful completion of the
   request.

At the moment 200 `OK` (or 204 `No Content`) is always returned. It would be nice to have a way to indicate that a resource was created.

**Comment by jkarni** [comment]
Closing this as a duplicate of #190 . For people who might come across is, currently the suggested way about it is defining your own combinator, with a `HasServer` instance that differs from the current one only in having 201 rather than 200 as the status code.

**Comment by i-am-the-slime** [comment]
I tried to backtrack to the actual solution but couldn't really find anything. Can you go into more detail about this "own combinator" approach? Thanks!

**Comment by alpmestan** [comment]
@i-am-the-slime Hi! [This PR](https://github.com/haskell-servant/servant/pull/276) changed all existing combinators to be simple type synonyms of [`Verb`](https://github.com/haskell-servant/servant/pull/276/files#diff-37b524dc8396a175938c788d35d9d2a6R24) with different parameters. You can use this to define your own `Post` that returns something else than *201* by defining a new type synonym similar to [servant's default `Post`](https://github.com/haskell-servant/servant/blob/master/servant/src/Servant/API/Verbs.hs#L39) but specifying another status code than 201. You need servant from git for now though to be able to use that as this will only be part of the next release.

**Comment by i-am-the-slime** [comment]
Ah, I'm using stack. I'll probably wait for the next LTS including this then and just return a 200 in any case.

**Comment by alpmestan** [comment]
You can use packages from git repos with stack as well, FWIW: http://docs.haskellstack.org/en/stable/yaml_configuration/ (scroll down a bit and look for "git")

**Comment by rvion** [comment]
eg:

```yaml
resolver: lts-5.5

# Local packages, usually specified by relative directory name
packages:
- .
- location:
    git: git@github.com:haskell-servant/servant.git
    commit: 5188e842a9288ac3986b30b93cb1a5d58cb2933d
  extra-dep: true
  subdirs:
  - servant
  - servant-blaze
  - servant-cassava
  - servant-client
  - servant-docs
  - servant-examples
  - servant-foreign
  - servant-js
  - servant-lucid
  - servant-mock
  - servant-server
```
