### ISSUE TITLE
Building for GHC 7.10.2

### ISSUE THREAD

**Issue by dmjio** [haskell-servant/servant#258]
I assume we'd like to build for multiple GHC versions w/ travis. If so, I have a script to do so (largely inspired by our current script, w/ modifications from hvr's script).

```yaml
language: c

# explicitly request container-based infrastructure
sudo: false

matrix:
  include:
    - env: GHCVER=7.8.4
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2
      addons: {apt: {packages: [ghc-7.10.2],sources: [hvr-ghc]}}
    - env: GHCVER=head
      addons: {apt: {packages: [ghc-head],  sources: [hvr-ghc]}}
  allow_failures:
     - env: GHCVER=head

before_install:
 - export STACK_YAML=stack-$GHCVER.yaml
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 # stack
 - mkdir -p ~/.local/bin
 - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar -xvzf -
 - mv stack ~/.local/bin
 - export PATH=~/.local/bin:$PATH

install:
 - stack build

script:
 - stack test

cache:
  directories:
    - $HOME/.stack
```

Then with corresponding yaml files (similar to what we have)
