### ISSUE TITLE
[tutorial] Migrate to current master.

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant#360]
The tutorial is currently broken for `servant-0.5`. Before the release, we have to fix that.

We should probably fix #358 first.

**Comment by soenkehahn** [comment]
Should be done in #355.

**Comment by soenkehahn** [comment]
Now the whole tutorial is at least compiling. We should read through it to make sure that the comments are also up-to-date. Here's a checklist that hopefully helps with that:

- [ ] ApiType.lhs
- [ ] Client.lhs
- [ ] Docs.lhs
- [ ] Javascript.lhs
- [ ] Server.lhs

(cc: @jkarni @kosmikus)

**Comment by rwobben** [comment]
Found another problem with the text. 
I did  serving a api -> a first example. 
I copy/paste everything and did a stack build. 

Then I saw this error message : Not in scope: data constructor ‘EmptyConfig’

Which seems to be right. EmptyConfig is never defined.

**Comment by soenkehahn** [comment]
Did you use `servant-0.5`?

**Comment by rwobben** [comment]
maybe a stupid question , but how can I check this ?

**Comment by fisx** [comment]
> maybe a stupid question , but how can I check this ?

```shell
grep ^version: */*.cabal
```

`git show` would also be interesting.

**Comment by rwobben** [comment]
grep ^version: */*.cabal
version:             0.1.0.0

git show does not have output.
I made my own project with stack.I did not clone the servant-example repo

**Comment by fisx** [comment]
sorry, I'm lacking context here.  the version of servant that you are using is named in the cabal file of the servant package.  not sure what cabal file you just grepped there, but it may be just the one from your project.

**Comment by rwobben** [comment]
It's the project version. 
In the cabal version there is only mentioned of servant-server without version numbers

**Comment by rwobben** [comment]
it seems that stack has installed 0.4.4.6 and not 0.5 which I had installed locally .
Anyone a tip how to solve this ?

**Comment by rvion** [comment]
yes, with something like that in your stack.yaml :

```yaml
packages:
- location: http://github.com/....
  subdirs:
  - servant-blaze
  - servant-cassava
  - servant-client
  - servant-docs
  - servant-examples
  - servant-foreign
  - servant-js
  - servant-lucid
  - servant-mock
  - servant-server
```
