### ISSUE TITLE
doctests test/Servant/API/ContentTypesSpec.hs:31:18: Ambiguous module name ‘Test.QuickCheck.Instances’

### ISSUE THREAD

**Issue by juhp** [haskell-servant/servant#488]
When building servant-0.6.1 in Stackage Nightly the doctest:

```
> /tmp/stackage-build8/servant-0.6.1$ dist/build/doctests/doctests

test/Servant/API/ContentTypesSpec.hs:31:18:
    Ambiguous module name ‘Test.QuickCheck.Instances’:
      it was found in multiple packages:
      quickcheck-instances-0.3.12@quick_0mPZBlf7BwNAlvdve9hZ5V checkers-0.4.4@check_JhpYt0kVr7M9KNTtZa50SB
```

**Comment by arianvp** [comment]
Could you try servant master out? I think we have fixed this in this pull request: https://github.com/haskell-servant/servant/pull/476


You can explicitly add it to your `stack.yaml` like this:
```
packages:
- location:
    git: git@github.com:haskell-servant/servant.git
    commit: fd26721feb172a9e8df2641e7b518a398aca5bb8
```
