### ISSUE TITLE
can't test servant-client with ghcjs

### ISSUE THREAD

**Issue by alexanderkjeldaas** [haskell-servant/servant#633]
servant-client has some ifdefs for ghc vs ghcjs, but I can't actually run

`stack test`.

This is annoying, because if you have a project using `stack-client` using ghcjs, `stack test` on the project will by default try to run the `servant-client` tests, which then will fail.

To repro:

```
resolver: nightly-2016-10-25

packages:
- location: '.'

compiler: ghcjs-0.2.1.820161025_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.820161025_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/untested/ghc-8.0-2016-10-25-nightly-2016-10-25-820161025.tar.gz
          sha1: ca05f23ab6af89803a9fa8ce7241ebdd2eee7dae


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.1"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
```
